"""add strumento_codice to soci

Revision ID: 4185ab91d4eb
Revises: e1f2a3b4c5d6
Create Date: 2026-06-18 23:33:42.906137

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4185ab91d4eb"
down_revision: str | Sequence[str] | None = "e1f2a3b4c5d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "soci", sa.Column("strumento_codice", sa.SmallInteger(), nullable=True)
    )
    op.create_foreign_key(None, "soci", "strumenti", ["strumento_codice"], ["codice"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "soci", type_="foreignkey")
    op.drop_column("soci", "strumento_codice")
    # ### end Alembic commands ###
