"""add_attivo_to_esterni

Revision ID: 5d29d2a49788
Revises: a7d2f1c93b08
Create Date: 2026-06-26 17:58:21.411133

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d29d2a49788"
down_revision: str | Sequence[str] | None = "a7d2f1c93b08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "esterni",
        sa.Column(
            "attivo", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    op.create_foreign_key(
        None, "voci_rendiconto", "sezioni_rendiconto", ["sezione_codice"], ["codice"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "voci_rendiconto", type_="foreignkey")
    op.drop_column("esterni", "attivo")
    # ### end Alembic commands ###
