"""add configurazioni_banda_anno

Revision ID: 8b23e062dcd8
Revises: 9c36141f6eed
Create Date: 2026-06-20 20:01:52.246488

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b23e062dcd8"
down_revision: str | Sequence[str] | None = "9c36141f6eed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configurazioni_banda_anno",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("banda_codice", sa.SmallInteger(), nullable=False),
        sa.Column("anno", sa.Integer(), nullable=False),
        sa.Column(
            "quota_annuale_attesa", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "saldo_iniziale_cassa", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "saldo_iniziale_banca", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("voce_contabilita_quote_id", sa.Integer(), nullable=True),
        sa.Column("chiuso", sa.Boolean(), nullable=False),
        sa.Column("data_chiusura", sa.DateTime(), nullable=True),
        sa.Column("chiuso_da_utente_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["banda_codice"], ["bande.codice"], name="fk_cfg_banda_anno_banda_codice"
        ),
        sa.ForeignKeyConstraint(
            ["chiuso_da_utente_id"],
            ["utenti.id"],
            name="fk_cfg_banda_anno_chiuso_da_utente_id",
        ),
        sa.ForeignKeyConstraint(
            ["voce_contabilita_quote_id"],
            ["voci_contabilita.id"],
            name="fk_cfg_banda_anno_voce_contabilita_quote_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "banda_codice", "anno", name="uq_configurazione_banda_anno"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("configurazioni_banda_anno")
    # ### end Alembic commands ###
