"""add banda_codice to spartiti

Revision ID: 9c36141f6eed
Revises: f2a4c6b8d0e1
Create Date: 2026-06-20 15:19:47.774953

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c36141f6eed"
down_revision: str | Sequence[str] | None = "f2a4c6b8d0e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spartiti", sa.Column("banda_codice", sa.SmallInteger(), nullable=False)
    )
    op.create_foreign_key(
        "spartiti_banda_codice_fkey", "spartiti", "bande", ["banda_codice"], ["codice"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("spartiti_banda_codice_fkey", "spartiti", type_="foreignkey")
    op.drop_column("spartiti", "banda_codice")
    # ### end Alembic commands ###
