"""create iscrizioni table

Revision ID: c86932530e9d
Revises: 34b80795ad5a
Create Date: 2026-06-06 19:39:36.871529

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c86932530e9d"
down_revision: str | Sequence[str] | None = "34b80795ad5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iscrizioni",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("socio_id", sa.Integer(), nullable=False),
        sa.Column("anno", sa.Integer(), nullable=False),
        sa.Column("quota_dovuta", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quota_pagata", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("stato_pagamento", sa.String(length=20), nullable=False),
        sa.Column("data_iscrizione", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["socio_id"],
            ["soci.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("iscrizioni")
    # ### end Alembic commands ###
